services:
  - type: web
    name: weather-forecast
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
